name: sport_tube
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  sqlite3_flutter_libs: ^0.5.20
  go_router: ^13.2.2
  path: ^1.9.0
  path_provider: ^2.1.2 
  riverpod_annotation: ^2.3.5 
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.16.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
